
import alanine
import arginine
import asparagine
import asparticacid
import benzene
import butane
import cysteine
import ethane
import glutamicacid
import glutamine
import glycine
import heptane
import hexane
import histidine
import isoleucine
import leucine
import lysine
import methane
import methionine
import octane
import pentane
import proline
import propane
import serine
import styrene
import threonine
import toluene
import tryptophan
import tyrosine
import valine

